name: "Update"

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@v11"
      - uses: "DeterminateSystems/magic-nix-cache-action@v6"

      - name: "Generating & running nvfetcher"
        run: |
          #!/usr/bin/env nix
          #!nix develop . --command bash
          nvfetcher -f '^nvim-treesitter$'
          echo 'Updating nvfetcher.toml...'
          nvim -l ./generate-nvfetcher.lua
          echo 'Fetching new plugin versions...'
          nvfetcher

      - name: "Commit changes"
        uses: "EndBug/add-and-commit@v9"
        with:
          message: "chore: update plugins"
          default_author: github_actions
