name: "Update"

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/flake-checker-action@v8"

      - uses: "DeterminateSystems/update-flake-lock@v23"

      - uses: "DeterminateSystems/nix-installer-action@v11"
      - uses: "DeterminateSystems/magic-nix-cache-action@v6"

      - name: "Generating & running nvfetcher"
        run: ./.github/workflows/scripts/update.sh

      - name: "Commit changes"
        uses: "EndBug/add-and-commit@v9"
        with:
          message: "chore: update plugins"
          default_author: "github_actions"
